# Compatibilidad para teclados y hardware de Apple Mac (Intel x86_64)
# Configurado para Equalrch Linux por Alfredo Dzul

# fnmode=2 : Las teclas F1-F12 funcionan primariamente como brillo, volumen y multimedia
# swap_opt_cmd=1 : Intercambia Alt y Command para que coincida con el layout estándar de PC
options hid_apple fnmode=2 swap_opt_cmd=1
