[Seat:*]
autologin-guest=false
autologin-user=liveuser
autologin-user-timeout=0
autologin-session=xfce
user-session=xfce
greeter-session=lightdm-gtk-greeter
pam-service=lightdm
pam-autologin-service=lightdm-autologin
allow-empty-passwords=true
