# Configuracion del Greeter LightDM para Dzulux Linux
# Disenado por Alfredo Dzul

[greeter]
background = /usr/share/backgrounds/dzulux/dzulux-wallpaper.svg
theme-name = Materia-dark
icon-theme-name = Papirus-Dark
font-name = Inter 10
indicators = ~host;~spacer;~clock;~power
clock-format = %a %d %b, %H:%M
user-background = false
hide-user-image = false
