# Optimizaciones del Kernel para Equipos de Bajo Rendimiento y Laptops
# Dzulux Linux - Disenado por Alfredo Dzul

# Swappiness optimizado para zRAM (prioriza swap ultrarrapido en RAM sobre disco)
vm.swappiness = 180

# Evita picos de congelamiento al escribir en discos lentos (HDD / eMMC)
vm.vfs_cache_pressure = 50
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
vm.page-cluster = 0
